import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/context/ReactQueryProvider";
import { Toaster } from "@/components/ui/toaster";

import ReactI18nextProvider from "@/context/ReactI18nextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactI18nextProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster />
        </ReactI18nextProvider>
      </body>
    </html>
  );
}
